/// Flutter icons DrdchatCustomIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DrdchatCustomIcons
///      fonts:
///       - asset: fonts/DrdchatCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DrdchatCustomIcons {
  DrdchatCustomIcons._();

  static const _kFontFam = 'DrdchatCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData door_exit = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData door_enter = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kick = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
